/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "fau_coordinate_t.h"

static int __fau_coordinate_t_hash_computed;
static int64_t __fau_coordinate_t_hash;

int64_t __fau_coordinate_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __fau_coordinate_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__fau_coordinate_t_get_hash };
    (void) cp;

    int64_t hash = 0x914be4f12bf3c28bLL
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __fau_coordinate_t_get_hash(void)
{
    if (!__fau_coordinate_t_hash_computed) {
        __fau_coordinate_t_hash = __fau_coordinate_t_hash_recursive(NULL);
        __fau_coordinate_t_hash_computed = 1;
    }

    return __fau_coordinate_t_hash;
}

int __fau_coordinate_t_encode_array(void *buf, int offset, int maxlen, const fau_coordinate_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].mode), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].count), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].traject, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int fau_coordinate_t_encode(void *buf, int offset, int maxlen, const fau_coordinate_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __fau_coordinate_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __fau_coordinate_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __fau_coordinate_t_encoded_array_size(const fau_coordinate_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].mode), 1);

        size += __int16_t_encoded_array_size(&(p[element].count), 1);

        size += __float_encoded_array_size(p[element].traject, p[element].count);

    }
    return size;
}

int fau_coordinate_t_encoded_size(const fau_coordinate_t *p)
{
    return 8 + __fau_coordinate_t_encoded_array_size(p, 1);
}

int __fau_coordinate_t_decode_array(const void *buf, int offset, int maxlen, fau_coordinate_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].mode), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].count), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].traject = (float*) lcm_malloc(sizeof(float) * p[element].count);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].traject, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __fau_coordinate_t_decode_array_cleanup(fau_coordinate_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].mode), 1);

        __int16_t_decode_array_cleanup(&(p[element].count), 1);

        __float_decode_array_cleanup(p[element].traject, p[element].count);
        if (p[element].traject) free(p[element].traject);

    }
    return 0;
}

int fau_coordinate_t_decode(const void *buf, int offset, int maxlen, fau_coordinate_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __fau_coordinate_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __fau_coordinate_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int fau_coordinate_t_decode_cleanup(fau_coordinate_t *p)
{
    return __fau_coordinate_t_decode_array_cleanup(p, 1);
}

int __fau_coordinate_t_clone_array(const fau_coordinate_t *p, fau_coordinate_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].mode), &(q[element].mode), 1);

        __int16_t_clone_array(&(p[element].count), &(q[element].count), 1);

        q[element].traject = (float*) lcm_malloc(sizeof(float) * q[element].count);
        __float_clone_array(p[element].traject, q[element].traject, p[element].count);

    }
    return 0;
}

fau_coordinate_t *fau_coordinate_t_copy(const fau_coordinate_t *p)
{
    fau_coordinate_t *q = (fau_coordinate_t*) malloc(sizeof(fau_coordinate_t));
    __fau_coordinate_t_clone_array(p, q, 1);
    return q;
}

void fau_coordinate_t_destroy(fau_coordinate_t *p)
{
    __fau_coordinate_t_decode_array_cleanup(p, 1);
    free(p);
}

int fau_coordinate_t_publish(lcm_t *lc, const char *channel, const fau_coordinate_t *p)
{
      int max_data_size = fau_coordinate_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = fau_coordinate_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _fau_coordinate_t_subscription_t {
    fau_coordinate_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void fau_coordinate_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    fau_coordinate_t p;
    memset(&p, 0, sizeof(fau_coordinate_t));
    status = fau_coordinate_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding fau_coordinate_t!!!\n", status);
        return;
    }

    fau_coordinate_t_subscription_t *h = (fau_coordinate_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    fau_coordinate_t_decode_cleanup (&p);
}

fau_coordinate_t_subscription_t* fau_coordinate_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    fau_coordinate_t_handler_t f, void *userdata)
{
    fau_coordinate_t_subscription_t *n = (fau_coordinate_t_subscription_t*)
                       malloc(sizeof(fau_coordinate_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 fau_coordinate_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg fau_coordinate_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int fau_coordinate_t_subscription_set_queue_capacity (fau_coordinate_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int fau_coordinate_t_unsubscribe(lcm_t *lcm, fau_coordinate_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe fau_coordinate_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

