/*
 * File: fromKinect.cpp
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Thu Jan  6 17:48:21 2011
 * 
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME fromKinect_RD_lores2
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS           0

#define NUM_OUTPUTS          2 // 
/* Output Port  0 */
#define OUT_PORT_0_NAME      d //
#define OUTPUT_0_WIDTH       140
#define OUTPUT_DIMS_0_COL    320
#define OUTPUT_0_DTYPE       uint16_T //
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           2-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME      r
#define OUTPUT_1_WIDTH       140
#define OUTPUT_DIMS_1_COL    320
#define OUTPUT_1_DTYPE       uint8_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_BUS_BASED      0
#define OUT_1_BUS_NAME       
#define OUT_1_DIMS           2-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
#define NPARAMS              0

#define SAMPLE_TIME_0        0 /*was INHERITED_SAMPLE_TIME*/
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0

#include "simstruc.h"

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
     if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
	 return; /* Parameter mismatch will be reported by Simulink */
     }

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    outputDimsInfo.width = OUTPUT_0_WIDTH;
    ssSetOutputPortDimensionInfo(S, 0, &outputDimsInfo);
    ssSetOutputPortMatrixDimensions( S ,0, OUTPUT_0_WIDTH, OUTPUT_DIMS_0_COL);
    ssSetOutputPortFrameData(S, 0, OUT_0_FRAME_BASED);
    ssSetOutputPortDataType(S, 0, SS_UINT16); //
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    outputDimsInfo.width = OUTPUT_1_WIDTH;
    ssSetOutputPortDimensionInfo(S, 1, &outputDimsInfo);
    ssSetOutputPortMatrixDimensions( S ,1, OUTPUT_1_WIDTH, OUTPUT_DIMS_1_COL);
    ssSetOutputPortFrameData(S, 1, OUT_1_FRAME_BASED);
    ssSetOutputPortDataType(S, 1, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    
    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    //ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
		//     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
   ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}


/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

/*----------------------BEGIN LOCAL FUNCTIONS-----------------------*/


/*----------------------END LOCAL FUNCTIONS-----------------------*/


/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/

#if defined _WIN32 || defined _WIN64/*If run for windows, do nothing (linux only)*/

static void mdlOutputs(SimStruct *S, int_T tid){}
static void mdlTerminate(SimStruct *S){}
#define MDL_START      
static void mdlStart(SimStruct *S){}

#else /*Running for linux*/ 

#include "simstruc.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <libfreenect.h>
#include <stdio.h>
#include <signal.h>
#include <string.h>
#include <stdlib.h>
#include <sys/time.h>
#include <pthread.h>
#include <unistd.h>

volatile sig_atomic_t kinRunning;
int kinFail,newFrame;
freenect_context *kinCtx;
freenect_device *kinDev;
pthread_t kinThread;
unsigned int kinD[140][320];
unsigned char  kinR[140][320];

double get_time()
{
	struct timeval cur;
	gettimeofday(&cur, NULL);
	return cur.tv_sec + cur.tv_usec / 1000000.;
}
int __nsleep(const struct timespec *req, struct timespec *rem)
{
    struct timespec temp_rem;
    if(nanosleep(req,rem)==-1)
        __nsleep(rem,&temp_rem);
    else
        return 1;
}


int msleep(unsigned long milisec)
{
    struct timespec req={0},rem={0};
    time_t sec=(int)(milisec/1000);
    milisec=milisec-(sec*1000);
    req.tv_sec=sec;
    req.tv_nsec=milisec*1000000L;
    __nsleep(&req,&rem);
    return 1;
}


void depth_cb(freenect_device *kinDev, void *data, uint32_t timestamp){ // Need to check size before doing bit wise opperations
    int i,j;
    unsigned char depl, deph;
    unsigned int dep;
    //printf("depth=%d\n",FREENECT_DEPTH_11BIT_SIZE);
    for (i=128000;i<486400;i+=4) //100*2*640=12800, 380*2*640=486400
    {
        j=i/4;
	depl = *((unsigned char*)data+i);
	deph = *((unsigned char*)data+i+1);
        dep = depl | deph<<8 ;
                if(dep>=1080){
                    dep=1080;
                }
                if(dep<410){
                    dep=410;
                }
        dep = (dep - 410); //depth is value [0 670]
        dep = 347500/(682.2-dep); //depth converted to mm (50-~3,000cm)
        kinD[(j/640)-50][j%320]= dep ;
//         kinD[j]= dep ;
    }
    newFrame++;
	
}

void rgb_cb(freenect_device *kinDev, void *data, uint32_t timestamp)
{
    int i,j;
    //printf("rgb=%d\n",FREENECT_VIDEO_RGB_SIZE);
    for (i=192000;i<729600;i+=6) //100*3*640=192000, 380*3*640=729600
    {
        j=i/6;
        kinR[(j/640)-50][j%320]=*((unsigned char*)data+i);
//         kinG[j/640][j%640]=*((unsigned char*)data+i+1);
//         kinB[j/640][j%640]=*((unsigned char*)data+i+2);
    }
    newFrame++;
}

void signal_cleanup(int num)
{
	
}


void *runLoop(void *ptr)
{
    while(kinRunning && freenect_process_events(kinCtx) >= 0)
    {
        //usleep(100000);
        //freenect_process_events(kinCtx);
        //printf("Loop\n");
    }
    printf("Out\n");

}


#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START) 
  /* Function: mdlStart =======================================================
   * Abstract:
   *    This function is called once at start of model execution. If you
   *    have states that should be initialized once, this is the place
   *    to do it.
   */
  static void mdlStart(SimStruct *S)
  {
    SS_SimMode mode= ssGetSimMode(S);
    if(mode==0)
    {
        kinFail=0;
        kinRunning=1;
        newFrame=0;

        memset (kinD,'0',44800);
        memset (kinR,'0',44800);
        
        /*-----INIT---------------*/

        if (freenect_init(&kinCtx, 0)) {
            printf("Error: Cannot get context\n");
            kinFail=1;
            return;
        }

        if (freenect_open_device(kinCtx, &kinDev, 0)) {
            printf("Error: Cannot get device\n");
            kinFail=1;
            return;
        }
        

        freenect_set_depth_mode(kinDev, freenect_find_depth_mode(FREENECT_RESOLUTION_MEDIUM, FREENECT_DEPTH_11BIT));
        freenect_set_depth_callback(kinDev, depth_cb);
        freenect_start_depth(kinDev);
        freenect_set_video_mode(kinDev, freenect_find_video_mode(FREENECT_RESOLUTION_MEDIUM, FREENECT_VIDEO_RGB));
        freenect_set_video_callback(kinDev, rgb_cb);
        freenect_start_video(kinDev);

        /*-----END INIT------------*/

        pthread_create( &kinThread, NULL, runLoop, NULL);
    }
    
    
    
  }
#endif /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    uint16_T       *depth  = (uint16_T *)ssGetOutputPortRealSignal(S,0); //change
    uint8_T        *r  = (uint8_T *)ssGetOutputPortRealSignal(S,1);
    SS_SimMode mode= ssGetSimMode(S);
    if(mode==0)
    {
        int i,j;
        if (newFrame>0) 
        {
            for(i=0;i<89600;i++)
            {
                j=i/2;
                depth[j]=kinD[j%140][j/140];
                r[j]=kinR[j%140][j/140];
                newFrame=0;
            }
         

        }
    }
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
   // SS_SimMode mode= ssGetSimMode(S);
   // if(mode==0)
   // {

        printf("Term\n");
        kinRunning= 0;
        freenect_stop_depth(kinDev);
        freenect_close_device(kinDev);
        freenect_shutdown(kinCtx);
   // }
    
}

#endif

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */

#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


