/*
 * File: Motors_Encoders_MrT.c
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Fri Jun 14 15:59:46 2013
 * 
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME Motors_Encoders_MrT
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS          2
/* Input Port  0 */
#define IN_PORT_0_NAME      Motor1
#define INPUT_0_WIDTH       1
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       uint8_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_BUS_BASED      0
#define IN_0_BUS_NAME       
#define IN_0_DIMS           1-D
#define INPUT_0_FEEDTHROUGH 1
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125
/* Input Port  1 */
#define IN_PORT_1_NAME      Motor2
#define INPUT_1_WIDTH       1
#define INPUT_DIMS_1_COL    1
#define INPUT_1_DTYPE       uint8_T
#define INPUT_1_COMPLEX     COMPLEX_NO
#define IN_1_FRAME_BASED    FRAME_NO
#define IN_1_BUS_BASED      0
#define IN_1_BUS_NAME       
#define IN_1_DIMS           1-D
#define INPUT_1_FEEDTHROUGH 1
#define IN_1_ISSIGNED        0
#define IN_1_WORDLENGTH      8
#define IN_1_FIXPOINTSCALING 1
#define IN_1_FRACTIONLENGTH  9
#define IN_1_BIAS            0
#define IN_1_SLOPE           0.125

#define NUM_OUTPUTS          2
/* Output Port  0 */
#define OUT_PORT_0_NAME      Encoder1
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       real_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME      Encoder2
#define OUTPUT_1_WIDTH       1
#define OUTPUT_DIMS_1_COL    1
#define OUTPUT_1_DTYPE       real_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_BUS_BASED      0
#define OUT_1_BUS_NAME       
#define OUT_1_DIMS           1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125

#define NPARAMS              0

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       1
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

/*
extern void Motors_Encoders_MrT_Outputs_wrapper(const uint8_T *Motor1,
                          const uint8_T *Motor2,
                          real_T *Encoder1,
                          real_T *Encoder2);*/

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
     if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
	 return; /* Parameter mismatch will be reported by Simulink */
     }

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /*Input Port 0 */
    ssSetInputPortWidth(S,  0, INPUT_0_WIDTH); /* */
    ssSetInputPortDataType(S, 0, SS_UINT8);
    ssSetInputPortComplexSignal(S,  0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /*Input Port 1 */
    ssSetInputPortWidth(S,  1, INPUT_1_WIDTH); /* */
    ssSetInputPortDataType(S, 1, SS_UINT8);
    ssSetInputPortComplexSignal(S,  1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

# define MDL_SET_INPUT_PORT_FRAME_DATA
static void mdlSetInputPortFrameData(SimStruct  *S, 
                                     int_T      port,
                                     Frame_T    frameData)
{
    ssSetInputPortFrameData(S, port, frameData);
}
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

/* ******************************************************************
 * This is where the matlab setup code stops*************************
 *******************************************************************/

#ifdef _WIN32 || _WIN64/*If run for windows, do nothing (linux only)*/

static void mdlOutputs(SimStruct *S, int_T tid){}
static void mdlTerminate(SimStruct *S){}
#define MDL_START      
static void mdlStart(SimStruct *S){}
#else /*Running for linux*/ 

    int fd; /* File descriptor for the port */
    
#include <stdio.h>    /* Standard input/output definitions */
#include <stdlib.h> 
#include <stdint.h>   /* Standard types */
#include <string.h>   /* String function definitions */
#include <unistd.h>   /* UNIX standard function definitions */
#include <fcntl.h>    /* File control definitions */
#include <errno.h>    /* Error number definitions */
#include <termios.h>  /* POSIX terminal control definitions */
#include <sys/ioctl.h>
#include <getopt.h>
#include <time.h>

#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START) 
  /* Function: mdlStart =======================================================
   * Abstract:
   *    This function is called once at start of model execution. If you
   *    have states that should be initialized once, this is the place
   *    to do it.
   */
  static void mdlStart(SimStruct *S)
  {
     /*Setup USB serial connection*/
	/*The following lines are done automatically at startup due to installed usbHostConf scrip*/
    //int j
    /*j=system("insmod /media/mmc2/usbserial.ko");
    j=system("insmod /media/mmc2/ftdi_sio.ko");
    j=system("echo host > /sys/devices/platform/musb_hdrc/mode");*/
   // system("insmod /matlab_includes/rtw/c/rlnx/rlnx_source/usbserial.ko");
    //system("insmod /matlab_includes/rtw/c/rlnx/rlnx_source/ftdi_sio.ko");
    //system("echo host > /sys/devices/platform/musb_hdrc/mode");
    fd = open("/dev/ttyUSB0", O_RDWR | O_NOCTTY | O_NDELAY);
    if (fd == -1)
    {

	perror("open_port: Unable to open /dev/ttyUSB0 - ");
	fd = open("/dev/ttyUSB1", O_RDWR | O_NOCTTY | O_NDELAY);
	if (fd == -1)
	{
		perror("open_port: Unable to open /dev/ttyUSB1 - ");
	}
     }
/*	else
    fcntl(fd, F_SETFL, 0);*/
     struct termios options;
    if (tcgetattr(fd, &options) < 0) {
        perror("init_serialport: Couldn't get term attributes");
        goto OUT;
    }
    /*BAUD RATE SET, MUST MATCH ARDUINOS!!!*/
    /*cfsetispeed(&options, B115200);
    cfsetospeed(&options, B115200);*/
    cfsetispeed(&options, B9600);
    cfsetospeed(&options, B9600);
    
    /* 8N1*/
    options.c_cflag &= ~PARENB; //Parity Enable
    options.c_cflag &= ~CSTOPB; //Send two stop bits, else one
    options.c_cflag &= ~CSIZE; //Character size
    options.c_cflag |= CS8; //8 bits
    options.c_cflag &= ~CRTSCTS;
    options.c_cflag |= CREAD | CLOCAL;  /* turn on READ & ignore ctrl lines*/
    options.c_iflag &= ~(IXON | IXOFF | IXANY); /* turn off s/w flow ctrl*/

    options.c_lflag &= ~(ICANON | ECHO | ECHOE | ISIG); 
    options.c_oflag &= ~OPOST; /* make raw*/
    options.c_cflag &= ~HUPCL;/* NEW ADDITION, DISSABLE HANGUP ON CLOSE*/
    /* see: http://unixwiz.net/techtips/termios-vmin-vtime.html
    options.c_cc[VMIN]  = 0;
    options.c_cc[VTIME] = 20;*/
    if( tcsetattr(fd, TCSANOW, &options) < 0) {
        perror("init_serialport: Couldn't set term attributes");
        goto OUT;
    }

    
    sleep(1);/*Pause for one second to assure connection*/


    int jwrite = 0, jread = 0;
    char M0msg = 0x00;
    char E0msg[20];
    jwrite=write(fd,&M0msg,1);    
    usleep(5000);
    jread=read(fd,&E0msg,20);
    
    while(jread == -1)
    {
        jwrite=write(fd,&M0msg,1);
        usleep(5000);
        jread=read(fd,&E0msg,20);
    }
   printf("Serial Port Setup"); 

        /*END SERIAL LINE INTIALIZATION-------------------*/
OUT:;
  }
#endif /*  MDL_START */

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType( S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
 ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const uint8_T   *Motor1  = (const uint8_T*) ssGetInputPortSignal(S,0);
    const uint8_T   *Motor2  = (const uint8_T*) ssGetInputPortSignal(S,1);
    real_T        *Encoder1  = (real_T *)ssGetOutputPortRealSignal(S,0);
    real_T        *Encoder2  = (real_T *)ssGetOutputPortRealSignal(S,1);

/*
    Motors_Encoders_Outputs_wrapper(Motor1, Motor2, Encoder1, Encoder2);
*/
    int kprint = 0;
    int jwrite = 0, jread = 0;
    char M1msg;/*Output config message to arduino (only pins to be polled are configed)*/
    char M2msg;
    char E1msg[20];
    char E2msg[20];
    signed short int E1, E2;
    char CODEN;
    
    
   /* Commented per the instructions on PBWORKS
    * Motors_Encoders_Outputs_wrapper(Motor1, Motor2, Encoder1, Encoder2);*/
    

    M1msg = Motor1[0];
    M2msg = Motor2[0];
    
    printf("M1 = %d",M1msg);
    printf("M2 = %d",M2msg);
    
    jwrite=write(fd,&M1msg,1);    
    usleep(5000);
    jread=read(fd,&E1msg,20);
    
    while(jread == -1)
    {
        jwrite=write(fd,&M1msg,1);
        usleep(5000);
        jread=read(fd,&E1msg,20);
    }

/*
    for (kprint = 0; kprint<jread;kprint++)
    {
        CODEN = E1msg[kprint] >> 6 & 0x03;
        printf("Data = %d \n",CODEN);
        CODEN = E1msg[kprint] & 0x3F;
        printf("VAL = %d \n",CODEN);

    }
*/

    
    
  
    E1 = ((short int)E1msg[1] & 0x003F) | (((short int)E1msg[0] << 6) & 0x0FC0);
    Encoder1[0] = (double)E1*2*3.14/2100;
    printf("E1 = %f \n",Encoder1[0]);
    
    usleep(5000);
    
    jwrite=write(fd,&M2msg,1);    
    usleep(5000);
    jread = read(fd,&E2msg,20);
    
    while(jread == -1)
    {
        jwrite=write(fd,&M2msg,1);
        usleep(5000);
        jread=read(fd,&E2msg,20);
    }
 

/*
       for (kprint = 0; kprint<jread;kprint++)
    {
        CODEN = E2msg[kprint] >> 6 & 0x03;
        printf("Data = %d \n",CODEN);
        CODEN = E2msg[kprint] & 0x3F;
        printf("Data = %d \n",CODEN);

    }
*/

 
    
 
    E2 = ((short int)E2msg[1] & 0x003F) | (((short int)E2msg[0] << 6) & 0x0FC0);
    Encoder2[0] = (double)E2*2*3.14/2100;
    printf("E2 = %f \n \n",Encoder2[0]);

  
    usleep(5000);
/*    for(ind = 1; ind<65000; ind++){}
    for(ind = 1; ind<65000; ind++){}
    for(ind = 1; ind<65000; ind++){}
    for(ind = 1; ind<65000; ind++){}*/

/*
    
    if (E1msgv[0] == ENCCODE){
        
        jread=read(fd,&E1msgv+1,2);       
        printf("E11 = %u \n",E1msgv[1]);
        printf("E12 = %u \n",E1msgv[2]);
        E2msg = (E1msgv[1] & 0x00FF)  | ( ( ( signed short int ) E1msgv[2] ) << 8 & 0xFF00 );}
    
    else {
        printf("Bad Reading E1 \n");
        jread=read(fd,&E1msgv+1,1); 
        jread=read(fd,&E1msgv+2,1); 
        E1msg = 0x0000;}

    printf("E1 = %hd \n",E1msg);
    
    jwrite=write(fd,&M2msg,1);    
    printf("M2 = %u \n",M2msg);
    
    jread=read(fd,&E2msgv,1);  
    printf("EC = %u \n",E2msgv[0]);
   
    if (E2msgv[0] == ENCCODE){
        jread=read(fd,&E2msgv+1,1); 
        printf("E21 = %u \n",E2msgv[1]);
        jread=read(fd,&E2msgv+2,1); 
        printf("EC = %u \n",E2msgv[2]);
        E2msg = (E2msgv[1] & 0x00FF)  | ( ( ( signed short int ) E2msgv[2] ) << 8 & 0xFF00 );}
    
    else {
       printf("Bad Reading");
        jread=read(fd,&E2msgv,1); 
        jread=read(fd,&E2msgv+1,1); 
        E2msg = 0x0000;}
        
    printf("E2 = %hd \n",E2msg);
*/
    
}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
         close(fd);
}

#endif

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


