/**********************************************************************************************************************
  Author: Gin Siu Cheng 
  File: myReceiver7.c 
  Date: 6/24/2014

  The following program is a C mex s function. Part of the code was generated by Matlab's 
  S Function Builder and other code that faciliates serial communication has been appended 
  into the file at the right locations. This is the 7th version of the code. The 6th version 
  works, however, it somehow causes Speedgoat to crash. This file attempts to fix this issue 
  by doing the following: 1. Flushing Buffers and 2. Hardware/Software Handshakes

  Output Variable: task (int32)
**********************************************************************************************************************/

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME myReceiver8
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS           0

#define NUM_OUTPUTS          1
/* Output Port  0 */
#define OUT_PORT_0_NAME      task
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       int32_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125

#define NPARAMS              0

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 0
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

//extern void myReceiver2_Outputs_wrapper(int32_T *task);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
     if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
	 return; /* Parameter mismatch will be reported by Simulink */
     }

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_INT32);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

/* ******************************************************************
 * This is where the matlab setup code stops*************************
 *******************************************************************/

#ifdef _WIN32 || _WIN64/*If run for windows, do nothing (linux only)*/

static void mdlOutputs(SimStruct *S, int_T tid){}
static void mdlTerminate(SimStruct *S){}
#define MDL_START      
static void mdlStart(SimStruct *S){}
#else /*Running for linux*/

#include <stdio.h> 		/* Standard I/O definitions */
#include <stdlib.h> 	
#include <unistd.h> 	/* UNIX standard function definitions */ 
#include <termios.h> 	/* POSIX terminal control definitions */  
#include <errno.h> 		/* Error number definitions */ 
#include <fcntl.h> 		/* File control definitions */ 

// Variables to include in the global section of the S-Function
	 int fd, i; // file descriptor for usb port 
    char readBuffer[10]; 
    char placeHolder[1]; 
    struct termios options;  

    
#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START) 
  /* Function: mdlStart =======================================================
   * Abstract:
   *    This function is called once at start of model execution. If you
   *    have states that should be initialized once, this is the place
   *    to do it.
   */
  static void mdlStart(SimStruct *S)
  {
    printf("MDLSTART"); 
    fd = open("/dev/ttyUSB0",O_RDONLY | O_NOCTTY | O_NDELAY);
				// O_NOCTTY = program don't want to be controlling terminal for port
        // O_NDELAY = program doesn't care what state the DCD signal line is in
        //            doesn't care if other side is connected or not yet

        if (fd == -1){ // file pter for serial not established
            printf("Can't Open Serial Port.Exiting Program...\n"); 
        } 	
        else{ // file pter for usb port established

            if(tcgetattr(fd,&options)<0){ // can't get current options for usb port
                printf("Cant get term attributes. Exiting Program...\n"); 
            }
            else{ // got current options for usb port 
                cfsetispeed(&options,B115200); // Set Input baud rates to 115200
                //cfsetospeed(&options,B115200); 
			
                // 8N1
                //options.c_cflag |= ~PARENB;  // Parity Enable
                //options.c_cflag &= ~PARODD;  // Parity Even
                options.c_cflag &= ~CSTOPB; // Stop Bit
                options.c_cflag &= ~CSIZE; // Character size
                options.c_cflag |= CS8; // 7 bits
                //options.c_cflag |= CNEW_RTSCTS; // Hardware Interrupt
                options.c_iflag |= (IXON | IXOFF | IXANY); // Software Interrupt
		        options.c_lflag |= (ICANON | ECHO | ECHOE); // Canonical Input
	            //options.c_iflag |= (INPCK | ISTRIP); // check and strip parity bit
                // Local Mode and Serial Data Receive
                options.c_cflag |= (CREAD | CLOCAL); // turn on read and ignore ctrl lines 
		
                if(tcsetattr(fd,TCSANOW,&options)<0){ // if can't set attributes 
                        printf("Can't set term attributes. Exiting Program...\n"); 
                }
			
                fcntl(fd,F_SETFL,FNDELAY);
                // FNDELAY option allows read to return immediate, causes read to return 
                // a 0 if no charaters are on the port
            }
        }
  }
#endif /*  MDL_START */

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
   ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    int32_T        *task  = (int32_T *)ssGetOutputPortRealSignal(S,0);
    fprintf(stdout,"Version24Cano: RECEIVING..\n"); 
    read(fd,&readBuffer,sizeof(readBuffer)); 
      if(readBuffer[0]== 'S' && readBuffer[1]== 'G') {
        fprintf(stdout,"ReadBufferInput:%s\n",readBuffer);
        placeHolder[0]=readBuffer[7]; 
        *task = atoi(placeHolder);  
      }
    
   
    for(i=0; i<10; i++)
        readBuffer[i]='K'; 

    tcflush(fd,TCIFLUSH);  
    //myReceiver2_Outputs_wrapper(task);
}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
    printf("MDLTERMINATE"); 
    close(fd); 
}
#endif
#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


