/*
 * File: serialMaster.c
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Tue Jun 24 20:14:30 2014
 * 
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME serialMaster3
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS          3
/* Input Port  0 */
#define IN_PORT_0_NAME      taskIN
#define INPUT_0_WIDTH       1
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       int32_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_BUS_BASED      0
#define IN_0_BUS_NAME       
#define IN_0_DIMS           1-D
#define INPUT_0_FEEDTHROUGH 1
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125
/* Input Port  1 */
#define IN_PORT_1_NAME      ang
#define INPUT_1_WIDTH       1
#define INPUT_DIMS_1_COL    1
#define INPUT_1_DTYPE       int32_T
#define INPUT_1_COMPLEX     COMPLEX_NO
#define IN_1_FRAME_BASED    FRAME_NO
#define IN_1_BUS_BASED      0
#define IN_1_BUS_NAME       
#define IN_1_DIMS           1-D
#define INPUT_1_FEEDTHROUGH 1
#define IN_1_ISSIGNED        0
#define IN_1_WORDLENGTH      8
#define IN_1_FIXPOINTSCALING 1
#define IN_1_FRACTIONLENGTH  9
#define IN_1_BIAS            0
#define IN_1_SLOPE           0.125
/* Input Port  2 */
#define IN_PORT_2_NAME      dist
#define INPUT_2_WIDTH       1
#define INPUT_DIMS_2_COL    1
#define INPUT_2_DTYPE       int32_T
#define INPUT_2_COMPLEX     COMPLEX_NO
#define IN_2_FRAME_BASED    FRAME_NO
#define IN_2_BUS_BASED      0
#define IN_2_BUS_NAME       
#define IN_2_DIMS           1-D
#define INPUT_2_FEEDTHROUGH 1
#define IN_2_ISSIGNED        0
#define IN_2_WORDLENGTH      8
#define IN_2_FIXPOINTSCALING 1
#define IN_2_FRACTIONLENGTH  9
#define IN_2_BIAS            0
#define IN_2_SLOPE           0.125

#define NUM_OUTPUTS          1
/* Output Port  0 */
#define OUT_PORT_0_NAME      taskOUT
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       int32_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125

#define NPARAMS              0

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 0
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"



/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
     if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
	 return; /* Parameter mismatch will be reported by Simulink */
     }

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /*Input Port 0 */
    ssSetInputPortWidth(S,  0, INPUT_0_WIDTH); /* */
    ssSetInputPortDataType(S, 0, SS_INT32);
    ssSetInputPortComplexSignal(S,  0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /*Input Port 1 */
    ssSetInputPortWidth(S,  1, INPUT_1_WIDTH); /* */
    ssSetInputPortDataType(S, 1, SS_INT32);
    ssSetInputPortComplexSignal(S,  1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /*Input Port 2 */
    ssSetInputPortWidth(S,  2, INPUT_2_WIDTH); /* */
    ssSetInputPortDataType(S, 2, SS_INT32);
    ssSetInputPortComplexSignal(S,  2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_INT32);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

# define MDL_SET_INPUT_PORT_FRAME_DATA
static void mdlSetInputPortFrameData(SimStruct  *S, 
                                     int_T      port,
                                     Frame_T    frameData)
{
    ssSetInputPortFrameData(S, port, frameData);
}
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

/* ******************************************************************
 * This is where the matlab setup code stops*************************
 *******************************************************************/

#ifdef _WIN32 || _WIN64/*If run for windows, do nothing (linux only)*/

static void mdlOutputs(SimStruct *S, int_T tid){}
static void mdlTerminate(SimStruct *S){}
#define MDL_START      
static void mdlStart(SimStruct *S){}
#else /*Running for linux*/

#include <stdio.h> 		/* Standard I/O definitions */
#include <stdlib.h> 	
#include <unistd.h> 	/* UNIX standard function definitions */ 
#include <termios.h> 	/* POSIX terminal control definitions */  
#include <errno.h> 		/* Error number definitions */ 
#include <fcntl.h> 		/* File control definitions */ 

// Variables to include in the global section of the S-Function
  int fd, i; // file descriptor for usb port 
  char readBuffer[15]; // Expected Message Length is Size 10 (including \r\n)
  char sendBuffer[]="LPTask:9 \r\n B1 Prob:1.2345 Color:1 Dist:1234 Ang:360 \r\n B2 Prob:2.3456 Color:2 Dist:2345 Ang:180 \r\n B3 Prob:3.4567 Color:3 Dist:3456 Ang:270 \r\n B4 Prob:4.5678 Color:4 Dist:4567 Ang:90 \r\n"; 
  char placeHolder[1]; char taskNum[1];
  struct termios options;  
    
#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START) 
  /* Function: mdlStart =======================================================
   * Abstract:
   *    This function is called once at start of model execution. If you
   *    have states that should be initialized once, this is the place
   *    to do it.
   */
  static void mdlStart(SimStruct *S)
  {
     fd = open("/dev/ttyUSB0",O_RDWR | O_NOCTTY | O_NDELAY);
		// O_NOCTTY = program don't want to be controlling terminal for port
        // O_NDELAY = program doesn't care what state the DCD signal line is in
        //            doesn't care if other side is connected or not yet

        if (fd == -1){ // file pter for serial not established
            printf("Can't Open Serial Port.Exiting Program...\n"); 
        } 	
        else{ // file pter for usb port established

            if(tcgetattr(fd,&options)<0){ // can't get current options for usb port
                printf("Cant get term attributes. Exiting Program...\n"); 
            }
            else{ // got current options for usb port 
                cfsetispeed(&options,B115200); // Set Input baud rates to 115200
                cfsetospeed(&options,B115200); // Set Output baud rates to 115200
			
                // 8N1
                // Note: Parity (even/odd) doesn't appear to work with the Speedgoat
                options.c_cflag &= ~CSTOPB; // Stop Bit
                options.c_cflag &= ~CSIZE; // Character size
                options.c_cflag |= CS8; // 8 bits
                //options.c_cflag |= CNEW_RTSCTS; // Hardware Interrupt doesn't appear to work with Speedgoat
                //options.c_iflag |= (IXON | IXOFF | IXANY); // Software Interrupt works with the Speedgoat
                //options.c_lflag |= (ICANON | ECHO | ECHOE); // Canonical Input works with the Speedgoat
                // Local Mode and Serial Data Receive
                options.c_cflag |= (CREAD | CLOCAL); // turn on read and ignore ctrl lines 
		
                if(tcsetattr(fd,TCSANOW,&options)<0){ // if can't set attributes 
                        printf("Can't set term attributes. Exiting Program...\n"); 
                }
			
                fcntl(fd,F_SETFL,FNDELAY);
                // FNDELAY option allows read to return immediate, causes read to return 
                // a 0 if no charaters are on the port
            }
        }
  }
#endif /*  MDL_START */

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType( S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
 ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const int32_T   *taskIN  = (const int32_T*) ssGetInputPortSignal(S,0);
    const int32_T   *ang  = (const int32_T*) ssGetInputPortSignal(S,1);
    const int32_T   *dist  = (const int32_T*) ssGetInputPortSignal(S,2);
    int32_T        *taskOUT  = (int32_T *)ssGetOutputPortRealSignal(S,0);

    *taskOUT = 0; 
    // Receive Portion of Serial
    printf("Receiving from Speedgoat\n"); 
    read(fd,&readBuffer,sizeof(readBuffer)); 
    printf("RECEIVED:%s\n",readBuffer); 
    if(readBuffer[0]== 'S' && readBuffer[1]== 'G') {
        placeHolder[0]=readBuffer[7]; 
        *taskOUT = atoi(placeHolder);  
        printf("TaskOut: %d\n",*taskOUT); 
    }
    for(i=0; i<10; i++)
        readBuffer[i]='K'; 
    fprintf(stdout,"Received from Speedgoat and Emptied Buffer\n");

    // Send Portion of Serial
    // Using the inputs: taskIn, ang, dist we convert those to characters to send to the Speedgoat
/*
    sprintf(taskNum,"%d",*taskIN); printf("Input Task:%c\n",taskNum[0]);
    sendBuffer[7]=taskNum[0]; 
    sprintf(taskNum,"%d",*ang); printf("Ang:%c\n",taskNum[0]); 
    sendBuffer[13]=taskNum[0]; 
    sprintf(taskNum,"%d",*dist); printf("Dist:%c\n",taskNum[0]); 
    sendBuffer[20]=taskNum[0]; */
    printf("Version2 Sending: %s to Speedgoat\n",sendBuffer); 
    write(fd,sendBuffer,sizeof(sendBuffer));
    printf("Message Sent\n"); 
    

    tcflush(fd,TCIOFLUSH);  
    /*
      tcflush() discards data written to the object referred to by fd but not transmitted, 
      or data received but not read, depending on the value of queue_selector:
      TCIFLUSH = flushes input queue
      TCOFLUSH = flushes output queue
      TCIOFLUSH = flushes both input/output queue
    */
}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
    printf("MDLTERMINATE"); 
    close(fd); 
}


#endif
#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


