/*
 * File: pot_readerV4.c
 *
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Real-Time Workshop, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Real-Time Workshop User's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 * Created: Wed Jun 25 18:55:58 2014
 *
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME TT_pot_readerV4
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS           0

#define NUM_OUTPUTS          1
/* Output Port  0 */
#define OUT_PORT_0_NAME      value
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       int32_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125

#define NPARAMS              0

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 0
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"



/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S) {
    
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Parameter mismatch will be reported by Simulink */
    }
    
    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);
    
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_INT32);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);
    
    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
            SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S) {
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

/* ******************************************************************
 * This is where the matlab setup code stops*************************
 *******************************************************************/

#ifdef _WIN32 || _WIN64/*If run for windows, do nothing (linux only)*/

static void mdlOutputs(SimStruct *S, int_T tid){}
static void mdlTerminate(SimStruct *S){}
#define MDL_START
static void mdlStart(SimStruct *S){}
#else /*Running for linux*/

#include <stdio.h> 		/* Standard I/O definitions */
#include <stdlib.h>
#include <unistd.h> 	/* UNIX standard function definitions */
#include <termios.h> 	/* POSIX terminal control definitions */
#include <errno.h> 		/* Error number definitions */
#include <fcntl.h> 		/* File control definitions */

// Global Variables
int fdPOT; // File Descriptor for the port
char readBuffer[8];
char potValue[4];
struct termios options;


#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START)
/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S) {
    fdPOT = open("/dev/ttyUSB.ARD1", O_RDWR | O_NOCTTY | O_NDELAY);
    if (fdPOT == -1) {
        
        perror("open_port: Unable to open /dev/ttyUSB.ARD1"); 
        fdPOT = open("/dev/ttyUSB.ARD2", O_RDWR | O_NOCTTY | O_NDELAY);
        if (fdPOT == -1) {
            perror("open_port: Unable to open /dev/ttyUSB.ARD2 - ");
        }
    }
    /*	else
     * fcntl(fd, F_SETFL, 0);*/
    struct termios options;
    if (tcgetattr(fdPOT, &options) < 0) {
        perror("init_serialport: Couldn't get term attributes");
        exit(1); 
    }
    /*BAUD RATE SET, MUST MATCH ARDUINOS!!!*/
    /*cfsetispeed(&options, B115200);
     * cfsetospeed(&options, B115200);*/
    cfsetispeed(&options, B9600);
    cfsetospeed(&options, B9600);
    
    /* 8N1*/
    options.c_cflag &= ~PARENB; //Parity Enable
    options.c_cflag &= ~CSTOPB; //Send two stop bits, else one
    options.c_cflag &= ~CSIZE; //Character size
    options.c_cflag |= CS8; //8 bits
    options.c_cflag &= ~CRTSCTS;
    options.c_cflag |= CREAD | CLOCAL;  /* turn on READ & ignore ctrl lines*/
    options.c_iflag &= ~(IXON | IXOFF | IXANY); /* turn off s/w flow ctrl*/
    
    options.c_lflag &= ~(ICANON | ECHO | ECHOE | ISIG);
    options.c_oflag &= ~OPOST; /* make raw*/
    options.c_cflag &= ~HUPCL;/* NEW ADDITION, DISSABLE HANGUP ON CLOSE*/
    /* see: http://unixwiz.net/techtips/termios-vmin-vtime.html
     * options.c_cc[VMIN]  = 0;
     * options.c_cc[VTIME] = 20;*/
    if( tcsetattr(fdPOT, TCSANOW, &options) < 0) {
        perror("init_serialport: Couldn't set term attributes");
        exit(1); 
    }
    
    
    //Clear buffer
    int jread = 0;
    int jwrite = 0;
    char Msg = 0;
    char P1msg[20];
    
    jwrite=write(fdPOT, &Msg, 1);
    usleep(10000);
    jread=read(fdPOT, &P1msg, 20);
    //printf("jread = %d \n",jread);
    while (jread == -1) {
        jwrite=write(fdPOT, &Msg, 1);
        usleep(10000);
        jread=read(fdPOT, &P1msg, 20);
        //printf("jread = %d \n",jread);
    }
    
    
    sleep(1);/*Pause for one second to assure connection*/
    
}
#endif /*  MDL_START */

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType) {
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S) {
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid) {
    int32_T        *value  = (int32_T *)ssGetOutputPortRealSignal(S, 0);
    
    int jread = 0;
    int jwrite = 0;
    char Msg = 0;

    char P1msg[20];
    signed short int P1;
    //char CODEN;
    
    jwrite=write(fdPOT, &Msg, 1);
    usleep(7500);
    jread=read(fdPOT, &P1msg, 20);
    P1 = ((short int)P1msg[0] & 0x00FF | (((short int)P1msg[1] << 8) & 0xFF00));
    
    //printf("jread = %d \n",jread);
    while (jread != 2 | P1 < 0 | P1 > 1023) {
        jwrite=write(fdPOT, &Msg, 1);
        usleep(7500);
        jread=read(fdPOT, &P1msg, 20);
        P1 = ((short int)P1msg[0] & 0x00FF | (((short int)P1msg[1] << 8) & 0xFF00));
        //printf("jread = %d \n",jread);
        //printf("potvalue = %s\n", P1Msg); 
    }
    
    
//    P1 = ((short int)P1msg[0] & 0x00FF | (((short int)P1msg[1] << 8) & 0xFF00));
    //P1 = (short int)P1msg[1] & 0x00FF;
    
/*
    if (P1 < 0 | P1 > 1023) {
        while (jread != 2) {
            jwrite=write(fdPOT, &Msg, 1);
            usleep(7500);
            jread=read(fdPOT, &P1msg, 20);
            //printf("jread = %d \n",jread);
        }
        P1 = ((short int)P1msg[0] & 0x00FF | (((short int)P1msg[1] << 8) & 0xFF00));
    }
*/
        
    value[0] = (long int)P1;
    
    //tcflush(fdPOT,TCIFLUSH);
}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S) {
    close(fdPOT);
}
#endif
#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


